In [1]:
import numpy as np

### Set the seed to 888

In [5]:
rng = np.random.default_rng(seed=888)

### Generate a one-dimensional array of size 100 with a normal distribution

In [6]:
one_dim_array = rng.normal(size=100)
print(one_dim_array)

[ 2.63038927e-01  5.02565261e-01 -6.03544630e-01  1.16105320e+00
  8.98071505e-01 -1.62755391e-01 -9.68181269e-01  5.05120942e-01
 -2.56207827e-01 -1.69745163e+00  1.69336869e+00  6.32799897e-03
  3.77968815e-03 -1.64070648e+00 -1.34108723e+00  7.12350868e-01
 -1.45685554e+00 -7.54516213e-01 -6.85843859e-01 -5.91052010e-01
  1.37411127e+00 -3.04630902e-01 -6.73853609e-01 -1.80586848e+00
 -5.40548771e-01 -4.91251392e-01  7.39680108e-01  2.71501625e-01
 -6.19142920e-02  1.17770521e+00  1.09704152e+00 -1.38911999e+00
 -6.95696437e-01  8.37534769e-01  9.06290500e-01  8.21394329e-01
  6.20728542e-01 -2.31346273e-01  3.93687465e-01  1.17078525e+00
  9.70762290e-02  4.77549317e-01  2.00284960e+00 -4.66757887e-01
 -3.69496733e-01 -4.61809244e-01  2.08655440e+00  9.88837783e-01
  1.02189658e+00  6.81389649e-01 -3.79780257e-01  6.79683068e-01
  8.88184795e-01 -1.08130766e+00 -5.22903695e-01 -6.96775922e-01
 -7.29571176e-01  1.34755592e+00  3.83166023e-02  1.80026204e+00
 -8.78028786e-01  3.48549

### Generate a two-dimensional array of size 8,8 with random integers from 1 to 10 - both included (same probability for each integer)

In [7]:
two_dim_array = rng.integers(1, 11, size = (8, 8))
print(two_dim_array)

[[ 4 10  4  2  2  1  3  4]
 [ 7  2  7  6  6 10  3  3]
 [10  9  9  7  9  5  9 10]
 [ 9  4  6 10 10 10  7  7]
 [ 5  5  7  3  8  5  7  3]
 [ 4  4  7 10  2 10  4  8]
 [ 2  8  7  2  2  6  5  4]
 [ 4  8  8  8  5  1  5  2]]


### Generate a three-dimensional of size 4,2,5 array with random integers from 1 to 17 - both included (same probability for each integer)

In [8]:
three_dim_array = rng.integers(1, 18, size = (4, 2, 5))
print(three_dim_array)

[[[ 8  4  2  8  4]
  [12 14 14 16 16]]

 [[ 8 12  5  1  7]
  [13 12  1  1 16]]

 [[ 9 11  4 16 12]
  [13  8 16  8 13]]

 [[ 5  9  8 13 12]
  [10 13  5  1 14]]]
