In [2]:
import numpy as np

### Generate an array with integers from 1 to 50

In [18]:
array1 = np.arange(1, 51)
print(array1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


### Generate an array with integers from 51 to 100

In [17]:
array2 = np.arange(51, 101)
print(array2)

[ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


### Using np.concatenate, concatenate the two arrays into: array([1,...,100])

In [19]:
array = np.concatenate((array1, array2))
print(array)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


### Reshape the previous array into:


    [[  1   2   3   4   5   6   7   8   9  10]
    [ 11  12  13  14  15  16  17  18  19  20]
                     ...
    [ 81  82  83  84  85  86  87  88  89  90]
    [ 91  92  93  94  95  96  97  98  99 100]]


In [20]:
reshape_array = array.reshape(10, 10)
print(reshape_array)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
