In [2]:
import numpy as np

### Generate a 2-dimensional array of size 9x9, with all elements initialized to 1 and of type int8

In [5]:
array = np.ones(shape = (9,9), dtype= np.int8)
print(array)

[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]


### Using slicing, create the following array:

    array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
    [1, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 1, 1, 1, 1, 0, 1],
    [1, 0, 1, 0, 0, 0, 1, 0, 1],
    [1, 0, 1, 0, 1, 0, 1, 0, 1],
    [1, 0, 1, 0, 0, 0, 1, 0, 1],
    [1, 0, 1, 1, 1, 1, 1, 0, 1],
    [1, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=np.int8)



In [10]:
pattern = array.copy()
pattern[1:8, 1:8] = 0
pattern[2:7, 2] = 1
pattern[2:7, -3] = 1
pattern[4,4] = 1
pattern[2, 2:7] = 1
pattern[-3, 2:7] = 1
print(pattern)

[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]]


### Using broadcasting create an output matrix based on the following two arrays:

    array_1 = np.array([1,2,3,4,5], dtype=np.int8)
    array_2 = np.array([1,2,3], dtype=np.int8)

Expected output:

    [[ 1  2  3]
     [ 2  4  6]
     [ 3  6  9]
     [ 4  8 12]
     [ 5 10 15]]

In [19]:
array_1 = np.array([1,2,3,4,5], dtype=np.int8).reshape(-1, 1)
print(array_1)
array_2 = np.array([1,2,3], dtype=np.int8)
print(array_2)
matrix = array_1 * array_2

print(matrix)

[[1]
 [2]
 [3]
 [4]
 [5]]
[1 2 3]
[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]]
