In [13]:
import numpy as np

from itertools import permutations

### reading data from the file.

In [ ]:
forecast = np.loadtxt('model_forecasts.txt', delimiter=',', dtype=float)
print(forecast)

[[  nan -2.3  -4.59 -4.83  3.13  4.13  1.07  2.29  0.44  4.35]
 [ 2.3    nan  3.57 -4.66  2.3  -3.24  3.63  0.41 -2.   -0.77]
 [ 4.59 -3.57   nan  1.47  1.15 -1.16  4.97  4.81  1.86  1.5 ]
 [ 4.83  4.66 -1.47   nan  0.25 -1.9  -0.14  3.89  4.34 -1.42]
 [-3.13 -2.3  -1.15 -0.25   nan  3.9  -2.73  1.23 -4.16  3.33]
 [-4.13  3.24  1.16  1.9  -3.9    nan -0.5   2.96 -2.69 -4.48]
 [-1.07 -3.63 -4.97  0.14  2.73  0.5    nan  4.42 -1.35 -3.95]
 [-2.29 -0.41 -4.81 -3.89 -1.23 -2.96 -4.42   nan  4.49 -0.4 ]
 [-0.44  2.   -1.86 -4.34  4.16  2.69  1.35 -4.49   nan  2.29]
 [-4.35  0.77 -1.5   1.42 -3.33  4.48  3.95  0.4  -2.29   nan]]


### clean data

In [ ]:
forecast = np.where(np.isnan(forecast), 0, forecast)
print(forecast)

[[ 0.   -2.3  -4.59 -4.83  3.13  4.13  1.07  2.29  0.44  4.35]
 [ 2.3   0.    3.57 -4.66  2.3  -3.24  3.63  0.41 -2.   -0.77]
 [ 4.59 -3.57  0.    1.47  1.15 -1.16  4.97  4.81  1.86  1.5 ]
 [ 4.83  4.66 -1.47  0.    0.25 -1.9  -0.14  3.89  4.34 -1.42]
 [-3.13 -2.3  -1.15 -0.25  0.    3.9  -2.73  1.23 -4.16  3.33]
 [-4.13  3.24  1.16  1.9  -3.9   0.   -0.5   2.96 -2.69 -4.48]
 [-1.07 -3.63 -4.97  0.14  2.73  0.5   0.    4.42 -1.35 -3.95]
 [-2.29 -0.41 -4.81 -3.89 -1.23 -2.96 -4.42  0.    4.49 -0.4 ]
 [-0.44  2.   -1.86 -4.34  4.16  2.69  1.35 -4.49  0.    2.29]
 [-4.35  0.77 -1.5   1.42 -3.33  4.48  3.95  0.4  -2.29  0.  ]]


### find the most intersting matches

In [ ]:
teams = np.arange(10)
min_cost = float('inf')
best_pairing = None


(0, 1, 2)
(0, 2, 1)
(1, 0, 2)
(1, 2, 0)
(2, 0, 1)
(2, 1, 0)
